### ISSUE TITLE
Energia 21 works on Linux with the EXP430G2ET

### ISSUE THREAD

**Issue by dlarue** [Andy4495/MSP-EXP430G2ET-Energia#1]
Thanks to finding your repo, I learned of Energia and was surprised to see it worked 'out of the box' with the EXP430G2ET on my Ubuntu 18.04 laptop.

I had borrowed a EXP430G2 and was using it with mspdebug to load the output from CCS 18.03. mspdebug currently doesn't support the EXP430G2ET so it seems I will be learning how to use DSLite since it appears that is what Energia is using.

Thanks for uploading your patch since it lead me to a possible solution.

**Comment by Andy4495** [comment]
I'm glad it proved helpful. As I note in the README, both CCS and TI's free [UniFlash][1] tool include dslite. With the updated G2ET LaunchPad, I think all the current LaunchPads are now supported by dslite. 

[1]: http://www.ti.com/tool/UNIFLASH
